---
on:
  workflow_call:
    inputs:
      docs_dir:
        type: string
        required: false
        default: docs/
      docker-compose-service:
        type: string
        required: false
        default: techdocs
      techdocs_bucket:
        type: string
        default: coop-techdocs-backstage-production-44f7
        required: false
      workload_identity_provider:
        type: string
        default: projects/1063410054216/locations/global/workloadIdentityPools/techdocs-pool/providers/techdocs-provider
        required: false
      workload_identity_service_account:
        type: string
        default: techdocs-publisher@backstage-production-44f7.iam.gserviceaccount.com
        required: false
    secrets: {}
concurrency:
  group: techdocs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    outputs:
      changed-markdown-files: ${{ steps.paths-filter.outputs.markdown_files }}
      changed-markdown: ${{ steps.paths-filter.outputs.markdown }}
      build: ${{ steps.paths-filter.outputs.build }}
      publish: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          base: main
          list-files: shell
          filters: |
            build:
              - catalog-info.yaml
              - mkdocs.yaml
              - docker-compose.yaml
              - docker-compose.yml
              - docker-compose/Dockerfile
              - "${{ inputs.docs_dir }}**/*.md"
              - "${{ inputs.docs_dir }}**/*.jpg"
              - "${{ inputs.docs_dir }}**/*.JPG"
              - "${{ inputs.docs_dir }}**/*.png"
              - "${{ inputs.docs_dir }}**/*.svg"
            markdown:
              - added|modified: "${{ inputs.docs_dir }}**/*.md"
  techdocs:
    needs: ["setup"]
    if: ${{ needs.setup.outputs.build == 'true' }}
    permissions:
      contents: read
      id-token: write
      packages: read
    runs-on: ubuntu-latest
    env:
      XDG_CACHE_HOME: ${{ github.workspace }}/.cache
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: auth
        uses: google-github-actions/auth@v2.1.0
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.workload_identity_service_account }}
          export_environment_variables: true
          create_credentials_file: true
      - name: Validate
        if: ${{ needs.setup.outputs.changed-markdown }}
        run: 'docker compose run --rm ${{ inputs.docker-compose-service }} validate MARKDOWN_FILES="${{ needs.setup.outputs.changed-markdown-files }}"'
      - name: Build site
        run: 'docker compose run --rm ${{ inputs.docker-compose-service }} build REPO_NAME="${{ github.repository }}" REPO_URL="${{ github.event.repository.html_url }}" EDIT_URI="edit/${{ github.event.repository.default_branch }}/${{ inputs.docs_dir }}"'
      - name: Publish site
        if: ${{ needs.setup.outputs.publish == 'true' }}
        run: 'docker compose run --rm ${{ inputs.docker-compose-service }} publish TECHDOCS_BUCKET="${{ inputs.techdocs_bucket }}"'
