---
on:
  workflow_call:
    inputs:
      docs_dir:
        type: string
        required: false
        default: docs/
      docker-compose-service:
        type: string
        required: false
        default: techdocs
      techdoc-bucket:
        type: string
        default: coop-techdocs-backstage-production-44f7
        required: false
      workload_identity_provider:
        type: string
        default: ""
        required: false
      workload_identity_service_account:
        type: string
        default: ""
        required: false
    secrets: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      changed-markdown-files: ${{ steps.paths-filter.outputs.markdown_files }}
      changed-markdown: ${{ steps.paths-filter.outputs.markdown }}
      build: ${{ steps.paths-filter.outputs.build }}
      publish: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: paths-filter
        with:
          base: main
          list-files: shell
          filters: |
            build:
              - '**/*.md'
              - catalog-info.yaml
              - mkdocs.yaml
            markdown:
              - '**/*.md'
  techdocs:
    needs: ['setup']
    if: ${{ needs.setup.outputs.build == 'true' }}
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    env:
      XDG_CACHE_HOME: ${{ github.workspace }}/.cache
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: auth
        uses: google-github-actions/auth@v0.8.1
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.workload_identity_service_account }}
          export_environment_variables: true
          create_credentials_file: true
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - run: gcloud auth list
      - uses: actions/cache@v3.0.10
        with:
          path: ${{ env.XDG_CACHE_HOME }}
          key: xdg-cache-${{ runner.os }}
          restore-keys: |
            xdg-cache-
      - name: Log in to ghcr.io
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Markdownlint
        if: ${{ needs.setup.outputs.changed-markdown }}
        run: |
          docker compose run --rm ${{ inputs.docker-compose-service }} markdownlint ${{ inputs.docs_dir }}
      - name: Linguistics Check
        if: ${{ needs.setup.outputs.changed-markdown }}
        run: |
          docker compose run --rm ${{ inputs.docker-compose-service }} vale ${{ needs.setup.outputs.changed-markdown-files }}
      - name: Build site
        run: |
          docker compose run --rm ${{ inputs.docker-compose-service }} techdocs-cli generate --no-docker
          tree site/
      - name: Publish site
        shell: bash
        run: |
          docker compose run --rm ${{ inputs.docker-compose-service }} techdocs-cli publish --publisher-type googleGcs --storage-name ${{ inputs.techdoc-bucket }} --entity default/Component/test-workflow
      - run: |
          sudo chown -R $(id -u) ${{ env.XDG_CACHE_HOME }}